# Netlify configuration for single-page application routing

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirect HTTP to HTTPS
[[redirects]]
  from = "http://llmredi3.netlify.app/*"
  to = "https://llmredi3.netlify.app/:splat"
  status = 301
  force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://parthgoai.pythonanywhere.com"
